#
# Makefile pour generer le client d'administration
#

# OBJS = adminFactory.o

# LOCAL_LIBS = -L ../Network  -L ../Threads -L ../IPC
# LOCAL_LIBS += -lnet  -lthrd -lipc
# CFLAGS += -I ../Network -I ../Threads -I ../IPC  -I ../Switch -I ../Logger

# #
# # Cible generale
# #

# all: adminFactory

# #
# # La cible de nettoyage
# #

# clean: 
# 	rm -f core *.o commutateur

# #
# # Les cibles pour l'executable
# #

# adminFactory: $(OBJS)
# 	$(CC) $(CFLAGS) -o adminFactory $(LOCAL_LIBS)

# adminFactory.o: adminFactory.c adminFactory.h 

